name: CI/CD .NET Core → Azure WebApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build, Test & Docker Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: dotnet restore
        run: dotnet restore ./Frock-backend.sln

      - name: dotnet build
        run: dotnet build ./Frock-backend.sln --configuration Release --no-restore

      - name: dotnet test
        run: dotnet test Frock-backend.test/**/*.csproj --no-build --configuration Release

      - name: Build Docker image
        run: |
          docker build \
            --file Frock-backend/Dockerfile \
            --tag frock-backend:latest \
            Frock-backend

  deploy:
    name: Publish & Deploy to Azure
    needs: build-and-test
    runs-on: windows-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: dotnet publish
        run: dotnet publish ./Frock-backend/Frock-backend.csproj \
              --configuration Release \
              --output ./publish